优化readme，service

diff --git a/set-lcd b/set-lcd
--- a/set-lcd
+++ b/set-lcd
@@ -243,6 +243,10 @@ remove() {
     
 }
 
+if [[ $EUID -ne 0 ]]; then
+    echo -e "\n\tError:This script must be run as root!\n" 
+    exit 1
+fi
 
 FUNCTION_NAME=$2
 ARGUMENT=$3
